version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-privileges.sql:/docker-entrypoint-initdb.d/init-privileges.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_container
    command: sh -c "python manage.py migrate &&
     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  frontend:
    build: ./frontend
    container_name: frontend_container
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data: