# Generated by Django 5.0.7 on 2024-08-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_seller'),
        ('users', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile', verbose_name='seller'),
        ),
    ]
